### ISSUE TITLE
Support for OpenHab v2.4

### ISSUE THREAD

**Issue by philip-p** [openhab/org.openhab.binding.bacnet#4] opened 2019-06-21 21:32 UTC
I am not sure if I am missing anything but dropping all jar files from this repo into "\openhab-2.4.0\addons" does not seem to work. I did enable legacy binding in the settings and restarted Openhab. 
Am I missing anything or is there no support yet for OH 2.4?

**Comment by plucpel** [comment] 2019-06-21 22:35
Did you enable the compatibility layer ? : https://www.openhab.org/docs/developer/legacy/compatibilitylayer.html

**Comment by splatch** [comment] 2019-06-22 09:37
> I am not sure if I am missing anything but dropping all jar files from this repo into "\openhab-2.4.0\addons" does not seem to work. I did enable legacy binding in the settings and restarted Openhab.
> Am I missing anything or is there no support yet for OH 2.4?

It works with OH 2.4 however, there are several dependencies which should be present in runtime before binding can be installed and fully activated. If you can please remove the binding from addons directory, enable legacy addons, restart openhab and once its fully started drop jar again. You can also try to start binding manually from the console by typing `start <bundle-id>` (you get it from the first column of `list` command output). 

If binding still fails to get activated please copy here some more diagnostic information, ie. what are constraints which are missing in your environment. You can grab these from output of `start` command or `openhab.log`.

**Comment by philip-p** [comment] 2019-06-23 00:44
Thanks for the replies, I was missing the compatibility layer. However, the binding still does not run because of missing packages. When doing `list` inside the console, it shows the "Bacnet4J Wrapper" is installed but it will not `start`.

My `JAVA_HOME` system path is pointing to `C:\Program Files\Java\jdk1.8.0_211`. It is the 64-bit version from Oracle Java.

Below is an excerpt from `openhab.log`. 

2019-06-22 19:04:38.133 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/C:/openhab-2.4.0/addons/api-1.1.0.jar
org.osgi.framework.BundleException: Could not resolve module: org.code-house.bacnet4j.api [248]
  Unresolved requirement: Import-Package: jssc

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [10:org.apache.felix.fileinstall:3.6.4]

**Comment by splatch** [comment] 2019-06-24 12:01
@philip-p You don't need to copy api.jar nor ip.jar files, all you need to drop ie. `org.openhab.binding.bacnet-1.13.0.jar`. Modules which you tried to install are embedded in BACnet binding archive. From your stacktrace it seems you are trying to install more things than needed.

**Comment by philip-p** [comment] 2019-06-24 15:54
@splatch  My bad. Thank you for the clarification. It installed correctly.

**Comment by splatch** [comment] 2020-01-08 11:33
Since solution was confirmed and problem is resolved I am closing the issue.

**Closed as completed by splatch** 2020-01-08 11:33 UTC
